export const FETCH_SHOPS_BEGIN = 'FETCH_SHOPS_BEGIN';
export const FETCH_SHOPS_SUCCESS = 'FETCH_SHOPS_SUCCESS';
export const FETCH_SHOPS_FAILURE = 'FETCH_SHOPS_FAILURE';
export const SETNEWLOCATION = 'SETNEWLOCATION'
